### ISSUE TITLE
 how_can_we_be_so_dense - How to modify to generate binary encodings?

### ISSUE THREAD

**Issue by kyoungrok0517** [numenta/htmpapers#31]
Hi, I'm interested in your HTM Spatial Pooler and the paper in the title.

Here's the question: the `SparseNet` introduced in the paper generates sparse _scalar_ vectors. But the original HTM generates _binary_ vectors. Can I modify the SparseNet to do the same??

**Comment by subutai** [comment]
> the `SparseNet` introduced in the paper generates sparse _scalar_ vectors. But the original HTM generates _binary_ vectors. Can I modify the SparseNet to do the same??

Hi @kyoungrok0517 - thanks for the note. You are right about the previous HTM algorithms. Those ones used a Hebbian learning algorithm. In this paper we use backpropagation, so scalar vectors are a requirement.

**Comment by kyoungrok0517** [comment]
Hi, thanks for the response. I'd be much appreciated if you answer one more question.

* What would be the best way to generate binary sparse vectors using `SparseNet`? Will it be enough to just make non-zero elements to 1 and the rest 0?

**Comment by kyoungrok0517** [comment]
Hi, thanks for the response. I'd be much appreciated if you answer one more question.

* What would be the best way to generate binary sparse vectors using SparseNet? Will it be enough to just make non-zero elements to 1 and the rest 0?

**Comment by uhfai** [comment]
Based on the Sparsenet paper, the sparse matrix encodings are real values
and continuous. So no, one and zero encoding is insufficient.

See paper at:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.391.4486&rep=rep1&type=pdf

Let me know if you have any questions.

Happy holidays.

Bart

**Comment by kyoungrok0517** [comment]
Thanks for pointing :)

2019년 12월 18일 (수) 오후 11:46, uhfai <notifications@github.com>님이 작성:
