### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bainro** [numenta/htmpapers#38]
Hi, I followed the README, but when running:

`python run.py -e prototype_10`

I get the following error:

![image](https://user-images.githubusercontent.com/31903812/144966478-0af927af-3046-4b93-9963-88cdd2dd78aa.png)

**Comment by bainro** [comment]
also, there's no prototype.py in experiments/ either:

![image](https://user-images.githubusercontent.com/31903812/144966587-bcba6d4f-a130-4333-8a0c-d1ee76efd5a3.png)

**Comment by bainro** [comment]
I added an old, deleted experiments/profiler.py from [here](https://github.com/numenta/htmpapers/commit/fbfd42088d8e62ab332a946f6b2e5ffdc7bdf514#diff-0056166665bdd2fd3d72c18a218ab86ba03ee55bd89ac88536b362255b8a6aac).

experiments/prototype_10 still doesn't exist like suggested in the README, so I ran another one instead:

![image](https://user-images.githubusercontent.com/31903812/145080122-53aa81b9-b5e1-4ea4-9633-03b3f9bfe5a0.png)

**Comment by bainro** [comment]
Upgraded from ray==0.8.3 to 0.8.4 and it seems to be working now with the default_base experiment:

`python run.py -e default_base --local-mode`

Still don't know how to access the prototype experiments...

**Comment by karangrewal** [comment]
Hi bainro, I just updated this repository (#40) to address the problems you encountered. TLDR; the implementation wasn't up to date.

You should be able to run the prototype experiments now. However, you will also have to run the command `ray stop; ray start --head` after you activate the virtual environment and before you run any experiments. (I also updated the README to include this info.)

**Comment by bainro** [comment]
Thanks a bunch! Excited to give it a try :)

**Comment by bainro** [comment]
A lot easier to setup and run now! Thanks again Karan :)
